services:
  authelia:
    image: ghcr.io/authelia/authelia:latest
    container_name: authelia
    volumes:
      - ${FOLDER_FOR_DATA:?err}/authelia:/config
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}
    restart: unless-stopped

# NOTE: Authelia MUST NOT connect to the Gluetun VPN container

networks:
  default:
    name: mediastack
    external: true