version: '3'

services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    restart: always
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /tank/nextcloud:/mnt/ncdata
    ports:
      - 127.0.0.1:11000:11000
    networks:
      - proxy
    environment:
      - NEXTCLOUD_DATADIR=/mnt/ncdata
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=0.0.0.0

networks:
  proxy:
    external: true

volumes:
  nextcloud_aio_mastercontainer: