version: "3.3"
services:
  prometheus:
    image: prom/prometheus:v2.51.2
    container_name: prometheus
    env_file:
      - .env
    environment:
      PUID: ${PUID}
      GUID: ${GUID}
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data:/prometheus
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.entrypoints=http"
      - "traefik.http.routers.prometheus.rule=Host(`${PROMETHEUS_HOST_NAME}`)"
      - "traefik.http.routers.prometheus.middlewares=https-redirectscheme@file"
      - "traefik.http.routers.prometheus-secure.rule=Host(`${PROMETHEUS_HOST_NAME}`)"
      - "traefik.http.routers.prometheus-secure.tls=true"
      - "traefik.http.routers.prometheus-secure.service=prometheus"
      - "traefik.http.services.prometheusloadbalancer.server.port=9090"
      - "traefik.docker.network=proxy"

  node_exporter:
    image: quay.io/prometheus/node_exporter:latest
    container_name: node_exporter
    env_file:
      - .env
    networks:
      - proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node_exporter.entrypoints=http"
      - "traefik.http.services.node_exporter.loadbalancer.server.port=9100"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true