services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    env_file:
      - .env
    environment:
      - PUID=1000  # Set your user ID
      - PGID=1000  # Set your group ID
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data:/prometheus
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.entrypoints=http"
      - "traefik.http.routers.prometheus.rule=Host(`${PROMETHEUS_HOST_NAME}`)"
      - "traefik.http.routers.prometheus.middlewares=https-redirectscheme@file"
      - "traefik.http.routers.prometheus-secure.rule=Host(`${PROMETHEUS_HOST_NAME}`)"
      - "traefik.http.routers.prometheus-secure.tls=true"
      - "traefik.http.routers.prometheus-secure.service=prometheus"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.docker.network=proxy"

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "9100:9100"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node_exporter.entrypoints=http"
      - "traefik.http.services.node_exporter.loadbalancer.server.port=9100"
      - "traefik.http.routers.node_exporter-secure.rule=Host(`node-exporter.local.robhagen.net`)"
      - "traefik.http.routers.node_exporter-secure.tls=true"
      - "traefik.docker.network=proxy"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "3000:3000"  # Access Grafana via http://localhost:3000
    networks:
      - proxy
    volumes:
      - ./grafana:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=http"
      - "traefik.http.routers.grafana.rule=Host(`grafana.local.robhagen.net`)"
      - "traefik.http.routers.grafana.middlewares=https-redirectscheme@file"
      - "traefik.http.routers.grafana-secure.rule=Host(`grafana.local.robhagen.net`)"
      - "traefik.http.routers.grafana-secure.tls=true"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    command:
      - '--docker_only=true'
      - '--housekeeping_interval=30s'
      - '--disable_metrics=referenced_memory'
    privileged: true
    devices:
      - /dev/kmsg
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ports:
      - 9080:8080
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cadvisor.entrypoints=http"
      - "traefik.http.routers.cadvisor.rule=Host(`cadvisor.local.robhagen.net`)"
      - "traefik.http.services.cadvisor.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
    restart: unless-stopped

networks:
  proxy:
    external: true
