services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    env_file:
      - .env
    environment:
      - PUID=1000  # Set your user ID
      - PGID=1000  # Set your group ID
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data:/prometheus
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.entrypoints=http"
      - "traefik.http.routers.prometheus.rule=Host(`${PROMETHEUS_HOST_NAME}`)"
      - "traefik.http.routers.prometheus.middlewares=https-redirectscheme@file"
      - "traefik.http.routers.prometheus-secure.rule=Host(`${PROMETHEUS_HOST_NAME}`)"
      - "traefik.http.routers.prometheus-secure.tls=true"
      - "traefik.http.routers.prometheus-secure.service=prometheus"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.docker.network=proxy"

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node_exporter.entrypoints=http"
      - "traefik.http.services.node_exporter.loadbalancer.server.port=9100"
      - "traefik.http.routers.node_exporter-secure.rule=Host(`node-exporter.local.robhagen.net`)"
      - "traefik.http.routers.node_exporter-secure.tls=true"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true