global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'bohrbytes'
    static_configs:
      - targets: ['192.168.0.220:9100']

  - job_name: 'pihole'
    static_configs:
      - targets: ['192.168.0.222:9100']  # Update with pihole's local IP

  - job_name: 'bohrbytes_docker'
    static_configs:
      - targets: ['172.22.0.1:9323']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
