global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'bohrbytes'
    static_configs:
      - targets: ['node-exporter.local.robhagen.net:9100']

  - job_name: 'pihole'
    static_configs:
      - targets: ['pihole.local.robhagen.net:9100']  # Update with pihole's local IP