global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'bohrbytes'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'pihole'
    static_configs:
      - targets: ['192.168.0.222:9100']  # Update with pihole's local IP