version: '3'

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=OMWw1mAW4UkViWewUPac86YmfFgxSHQx+M8ZZPGiVXA=
      - WIREGUARD_ADDRESSES=10.71.224.145/32
      #- SERVER_COUNTRIES=Sweden, Netherlands
      #- SERVER_CITIES=Stockholm, Amsterdam

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbit
    network_mode: "service:wireguard"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ${FOLDER_FOR_DOCKER_DATA}/qbittorrent:/config
      - ${FOLDER_FOR_MEDIA}/data/torrents:/data
    depends_on:
      - wireguard
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.rule=Host(`qbit.local.robhagen.net`)"
      - "traefik.http.routers.qbittorrent.entrypoints=https"
      - "traefik.http.routers.qbittorrent.tls=true"
      - "traefik.http.routers.qbittorrent.tls.certresolver=cloudflare"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
      
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    ports:
      - 8989:8989
    volumes:
      - ${FOLDER_FOR_DOCKER_DATA}/sonarr:/config
      - ${FOLDER_FOR_MEDIA}:/data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.${DOMAIN}`)"
      - "traefik.http.routers.sonarr.entrypoints=http"
      - "traefik.http.routers.sonarr.middlewares=https-redirectscheme@file"
      - "traefik.http.routers.sonarr-secure.rule=Host(`sonarr.${DOMAIN}`)"
      - "traefik.http.routers.sonarr-secure.tls=true"
      - "traefik.http.routers.sonarr-secure.service=sonarr"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
    networks:
      - proxy

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ${FOLDER_FOR_DOCKER_DATA}/radarr:/config
      - ${FOLDER_FOR_MEDIA}:/data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.${DOMAIN}`)"
      - "traefik.http.routers.radarr.entrypoints=http"
      - "traefik.http.routers.radarr.middlewares=https-redirectscheme@file"
      - "traefik.http.routers.radarr-secure.rule=Host(`radarr.${DOMAIN}`)"
      - "traefik.http.routers.radarr-secure.tls=true"
      - "traefik.http.routers.radarr-secure.service=radarr"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
    networks:
      - proxy

  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ${FOLDER_FOR_DOCKER_DATA}/lidarr:/config
      - ${FOLDER_FOR_MEDIA}:/data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lidarr.rule=Host(`lidarr.${DOMAIN}`)"
      - "traefik.http.routers.lidarr.entrypoints=http"
      - "traefik.http.routers.lidarr.middlewares=https-redirectscheme@file"
      - "traefik.http.routers.lidarr-secure.rule=Host(`lidarr.${DOMAIN}`)"
      - "traefik.http.routers.lidarr-secure.tls=true"
      - "traefik.http.routers.lidarr-secure.service=lidarr"
      - "traefik.http.services.lidarr.loadbalancer.server.port=8686"
    networks:
      - proxy 

  overseerr:
    image: linuxserver/overseerr
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ${FOLDER_FOR_DOCKER_DATA}/overseerr:/config
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overseerr.rule=Host(`overseerr.${DOMAIN}`)"
      - "traefik.http.routers.overseerr.entrypoints=http"
      - "traefik.http.routers.overseerr.middlewares=https-redirectscheme@file"
      - "traefik.http.routers.overseerr-secure.rule=Host(`overseerr.${DOMAIN}`)"
      - "traefik.http.routers.overseerr-secure.tls=true"
      - "traefik.http.routers.overseerr-secure.service=overseerr"
      - "traefik.http.services.overseerr.loadbalancer.server.port=5055"
    networks:
      - proxy

  prowlarr:
      image: linuxserver/prowlarr:develop
      container_name: prowlarr
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=America/Chicago
      volumes:
        - ${FOLDER_FOR_DOCKER_DATA}/prowlarr:/config
      depends_on:
        - wireguard
      restart: unless-stopped
      network_mode: "service:wireguard"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.${DOMAIN}`)"
        - "traefik.http.routers.prowlarr.entrypoints=http"
        - "traefik.http.routers.prowlarr.middlewares=https-redirectscheme@file"
        - "traefik.http.routers.prowlarr-secure.rule=Host(`prowlarr.${DOMAIN}`)"
        - "traefik.http.routers.prowlarr-secure.tls=true"
        - "traefik.http.routers.prowlarr-secure.service=prowlarr"
        - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"

networks:
  proxy:
    external: true