---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Media:
    - Plex:
        href: http://plex.local.robhagen.net/
        description: Homepage is 😎
        icon: plex.svg
        server: my-docker
        container: plex
        widget:
            type: plex
            url: http://192.168.0.220:32400
            key: ${PLEX_TOKEN}
    - Overseer:
        href: http://overseerr.local.robhagen.net/
        description: Request your shows and media!
        icon: overseerr.svg 
        server: my-docker
        container: overseerr

- Data Science:
    - JupyterLab:
        href: http://jupyter.local.robhagen.net
        description: jupyterLab environment
        icon: jupyter.svg
        server: my-docker 
        container: jupyterlab

- Server Admin:
    - Pihole:
        href: https://pihole.local.robhagen.net
        description: local DNS server and ad-block
        icon: pi-hole.svg
        widget:
          type: pihole
          url: http://192.168.0.222
          key: ${PIHOLE_KEY}
    - Traefik:
        href: https://dashboard.local.robhagen.net
        description: reverse proxy management
        icon: traefik.svg
        server: my-docker
        container: traefik
        widget:
          type: traefik
          url: http://traefik:8080
    - Portainer:
        href: https://portainer.local.robhagen.net
        description: local portainer environment
        icon: portainer.svg
        server: my-docker
        container: portainer
    - Syncthing:
        href: https://syncthing.local.robhagen.net
        description: network file sync tools
        icon: syncthing.svg
        server: my-docker
        container: syncthing

- Stack Admin:
    - Sonarr:
        href: https://sonarr.local.robhagen.net/
        description: series management
        icon: sonarr.svg
        server: my-docker
        container: sonarr
        widget:
            type: sonarr
            url: https://192.168.0.220:8989
            key: 649cff2a58214e7a931f54a340a37e3e
            enableQueue: true # optional, defaults to false

    - Radarr:
        href: https://radarr.local.robhagen.net/
        description: movie management
        icon: radarr.svg
        server: my-docker
        container: radarr
        widget:
            type: radarr
            url: http://192.168.0.220:7878
            key: ${RADARR_KEY}
            enableQueue: true # optional, defaults to false

    - Lidarr:
        href: https://lidarr.local.robhagen.net/
        description: music management
        icon: lidarr.svg
        server: my-docker
        container: lidarr
    - Prowlarr:
        href: https://192.168.0.220:9696/
        description: request management
        icon: prowlarr.svg
        server: my-docker
        container: prowlarr

- Cloud Tools:
    - NextCloud:
        href: https://nextcloud.local.robhagen.net/
        description: cloud file suite
        icon: nextcloud.svg
        server: my-docker
        container: nextcloud-aio-nextcloud