---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Media:
    - Plex:
        href: http://plex.local.robhagen.net/
        description: Homepage is 😎
        icon: plex.svg
        server: my-docker
        container: plex
        widget:
            type: plex
            url: http://192.168.0.220:32400
            key: 6fwwMKVwUCpT72kuy_pB
    - Overseer:
        href: http://overseerr.local.robhagen.net/
        description: Request your shows and media!
        icon: overseerr.svg 
        server: my-docker
        container: overseerr
        widget: 
            type: overseerr
            url: http://192.168.0.220:5055
            key: MTcyNDcxMTIwNTg4MzI0MDYxMTU3LTA3YTctNDIxNC05MDk0LTE0ZjQxMDcwOWRmOA==

- Server Admin:
    - Pihole:
        href: https://pihole.local.robhagen.net
        description: local DNS server and ad-block
        icon: pi-hole.svg
        widget:
            type: pihole
            url: http://192.168.0.222
            key: 88d71cc66316cf49c8bd68e663d14b08a094e96a6bef5ae2716ac7b321629cabd
    - Traefik:
        href: https://dashboard.local.robhagen.net
        description: reverse proxy management
        icon: traefik.svg
        server: my-docker
        container: traefik
        widget:
            type: traefik
            url: http://traefik:8080
    - Portainer:
        href: https://portainer.local.robhagen.net
        description: local portainer environment
        icon: portainer.svg
        server: my-docker
        container: portainer

- Media Backend:
    - Sonarr:
        href: https://sonarr.local.robhagen.net/
        description: series management
        icon: sonarr.svg
        server: my-docker
        container: sonarr
        widget:
            type: sonarr
            url: http://192.168.0.220:8989
            key: 649cff2a58214e7a931f54a340a37e3e
            enableQueue: false # optional, defaults to false
    - Radarr:
        href: https://radarr.local.robhagen.net/
        description: movie management
        icon: radarr.svg
        server: my-docker
        container: radarr
        widget:
            type: radarr
            url: http://192.168.0.220:7878
            key: a905325db59743088fe7993af6b6d07a
            enableQueue: false # optional, defaults to false
    - Lidarr:
        href: https://lidarr.local.robhagen.net/
        description: music management
        icon: lidarr.svg
        server: my-docker
        container: lidarr
        widget:
            type: lidarr
            url: http://192.168.0.220:8686
            key: 1571648254c94b81b75adef85d7d089a
    - Prowlarr:
        href: https://192.168.0.220:9696/
        description: request management
        icon: prowlarr.svg
        server: my-docker
        container: prowlarr
        widget:
            type: prowlarr
            url: http://192.168.0.220:9696
            key: 84ceada06d7e4582b3577f5518f92e68
    - Sabnzbd:
        href: https://sabnzbd.local.robhagen.net/
        description: nzb client
        icon: sabnzbd.svg
        server: my-docker
        container: sabnzbd
        widget:
            type: sabnzbd
            url: http://192.168.0.220:8100
            key: 7292a0176d514e6287a478179a7ebcf0
    - Qbit:
        href: https://qbit.local.robhagen.net/
        description: nzb client
        icon: qbittorrent.svg
        server: my-docker
        container: sabnzbd
        widget:
            type: sabnzbd
            url: http://192.168.0.220:8200
            username: rob
            password: clea1211

- Cloud Apps:
    - NextCloud:
        href: https://nextcloud.local.robhagen.net/
        description: cloud file suite
        icon: nextcloud.svg
        server: my-docker
        container: nextcloud-aio-nextcloud
    - Syncthing:
        href: https://syncthing.local.robhagen.net
        description: network file sync tools
        icon: syncthing.svg
        server: my-docker
        container: syncthing
    - JupyterLab:
        href: http://jupyter.local.robhagen.net
        description: jupyterLab environment
        icon: jupyter.svg
        server: my-docker 
        container: jupyterlab